steps:
  # Clone repository from GitHub (for private repo)
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git clone https://$GITHUB_TOKEN@github.com/abukalam2909/K8s_microservices.git /workspace/repo
    secretEnv: ['GITHUB_TOKEN']

  # Build Docker Images
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/container1:${SHORT_SHA}'
      - '.'
    dir: '/workspace/repo/container1'
  
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/container2:${SHORT_SHA}'
      - '.'
    dir: '/workspace/repo/container2'

  # Push Images to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/container1:${SHORT_SHA}'
  
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/container2:${SHORT_SHA}'

  # Deploy to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - '/workspace/repo/kubernetes'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=my-gke-cluster'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/container1:${SHORT_SHA}'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/container2:${SHORT_SHA}'

secrets:
  - secretEnv:
      GITHUB_TOKEN: 'projects/$PROJECT_ID/secrets/github-token/versions/latest'

options:
  logging: CLOUD_LOGGING_ONLY
