apiVersion: apps/v1
kind: Deployment
metadata:
  name: container1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container1
  template:
    metadata:
      labels:
        app: container1
    spec:
      containers:
      - name: container1
        image: 'IMAGE_TAG_CONTAINER1'
        volumeMounts:
          - name: storage
            mountPath: "/AbuKalamBabuji_PV_dir"
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
          requests:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 6000
        env:
        - name: COMPUTE_SERVICE_HOST
          value: "container2-service"
        - name: COMPUTE_SERVICE_PORT
          value: "6001"
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: product-data-pvc