apiVersion: apps/v1
kind: Deployment
metadata:
  name: container2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container2
  template:
    metadata:
      labels:
        app: container2
    spec:
      containers:
      - name: container2
        image: 'IMAGE_TAG_CONTAINER2'
        volumeMounts:
          - name:  storage
            mountPath:  "/AbuKalamBabuji_PV_dir"
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
          requests:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 6001
      volumes:
        - name:  storage
          persistentVolumeClaim:
            claimName: product-data-pvc
