apiVersion: apps/v1
kind: Deployment
metadata:
  name: container2
spec:
  selector:
    matchLabels:
      app: container2
  template:
    metadata:
      labels:
        app: container2
    spec:
      containers:
      - name: container2
        image: abukalam/a3_container2:new_feature
        volumeMounts:
          - name:  storage
            mountPath:  "AbuKalamBabuji_PV_dir"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6001
      volumes:
        - name:  storage
          persistentVolumeClaim:
            claimName: product-data-pvc
