apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: product-data-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage